# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: José Dulanto
email: jose@dulan.to
description: > # this means to ignore newlines until "baseurl:"
  I'm a Ruby developer with 5 years on the field. I am here to help you code the
  next big thing! P.S. I’m also a human, let’s talk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jose.dulan.to" # the base hostname & protocol for your site
repository: josedulanto/josedulanto.github.io
twitter_username: josedulanto
github_username:  josedulanto
markdown: kramdown
